# Generated by Django 6.0.4 on 2026-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sport_type', models.CharField(choices=[('badminton', 'Badminton'), ('tennis', 'Tennis'), ('basketball', 'Basketball'), ('football', 'Football'), ('swimming', 'Swimming'), ('volleyball', 'Volleyball')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_start', models.TimeField()),
                ('availability_end', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
